name: clean_disk_network
description: Network infrastructure adapters for Clean Disk.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.5

dependencies:
  abstract_http_client:
    path: ../abstract_http_client
  dio_http_client:
    path: ../dio_http_client
  clean_disk_core: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
